### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference 错误

### ISSUE THREAD

**Issue by King-Of-Knights** [maxduke/go-chatgpt-api#78]
请大佬帮忙看看
```
[36mINFO[0m[0000] [1;32mHealth Check is disabled[0m
[36mINFO[0m[0001] [1;32maccessToken is updated[0m
[36mINFO[0m[0001] [1;32mPUID is updated[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9be878]

goroutine 34 [running]:
github.com/maxduke/go-chatgpt-api/api/chatgpt.CreateWSConn.func1({0x45186a?, 0x1637be0?}, {0xaf6ae1, 0x3}, {0xc001742c80, 0x39})
/app/api/chatgpt/api.go:747 +0xf8
github.com/gorilla/websocket.(*Dialer).DialContext.func2({0xaf6ae1?, 0xc0000f19e0?}, {0xc001742c80?, 0x1067a00?})
/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/client.go:263 +0x43
github.com/gorilla/websocket.(*Dialer).DialContext.func5({0xaf6ae1?, 0xa40360?}, {0xc001742c80?, 0x18?})
/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/client.go:287 +0x44
github.com/gorilla/websocket.(*Dialer).DialContext(0xc0016547e0?, {0xc06e78, 0x1067a00}, {0xc001364480, 0x233}, 0x0)
/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/client.go:321 +0x12e4
github.com/gorilla/websocket.(*Dialer).Dial(...)
/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/client.go:117
github.com/maxduke/go-chatgpt-api/api/chatgpt.CreateWSConn({0xc001364480, 0x233}, 0xc0001c3f00, 0x0)
/app/api/chatgpt/api.go:757 +0xfe
github.com/maxduke/go-chatgpt-api/api/chatgpt.InitWSConn({0xc001630000, 0x4c3}, {0xc001362060, 0x24}, {0xc001362b70, 0x24})
/app/api/chatgpt/api.go:827 +0x4df
github.com/maxduke/go-chatgpt-api/api/imitate.CreateChatCompletions.func1()
/app/api/imitate/api.go:84 +0x74
created by github.com/maxduke/go-chatgpt-api/api/imitate.CreateChatCompletions in goroutine 32
/app/api/imitate/api.go:82 +0x785
```

**Comment by maxduke** [comment]
拉下最新镜像试试

**Comment by King-Of-Knights** [comment]
好了，感谢大大🤗🤗
